version: "3.8"

services:
  app:
    image: ${ECR_REPOSITORY_URL}:latest
    container_name: delivery-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

  # nginx 서비스
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: unless-stopped