spring.application.name=delivery-order-platform

# JPA
spring.jpa.database=PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Database
spring.datasource.url= ${db.url}
spring.datasource.username= ${db.user}
spring.datasource.password= ${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration-min=${JWT_ACCESS_TOKEN_EXP_MIN}
jwt.refresh-expiration-days=${JWT_REFRESH_TOKEN_EXP_DAYS}

# Gemini
gemini.api.url=${gemini.api.url}
gemini.api.key=${gemini.api.key}
ai.service.url=${ai.service.url}