spring.application.name=delivery-order-platform

# JPA
spring.jpa.database=PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Database
spring.datasource.url= ${DB_URL}
spring.datasource.username= ${DB_USER}
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration-min=${JWT_ACCESS_TOKEN_EXP_MIN}
jwt.refresh-expiration-days=${JWT_REFRESH_TOKEN_EXP_DAYS}

# Gemini
gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}
ai.service.url=${AI_SERVICE_URL}