spring.application.name=delivery-order-platform

# JPA
spring.jpa.database=PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Database
spring.datasource.url= ${db.url}
spring.datasource.username= ${db.user}
spring.datasource.password= ${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver